[main]
font=JetBrains Mono:size=14
dpi-aware=no
prompt="❯ "
icon-theme=Papirus
width=40
lines=10
horizontal-pad=20
vertical-pad=20
inner-pad=10

# --- BEHAVIOR ---
# This is the ONLY setting that controls closing on outside click.
exit-on-keyboard-focus-loss=yes

# 'layer=overlay' forces it to be the absolute top thing.
# If this still doesn't close on click, try changing this to 'top'
layer=top

[colors]
# 95% Opaque (Glass Effect)
background=3b4953f2
text=ebf4ddff
match=90ab8bff
selection=90ab8bff
selection-text=3b4953ff
selection-match=3b4953ff
border=90ab8bff

[border]
width=2
radius=20
